kind: Service
apiVersion: v1
metadata:
  name:  movie-analist-ui-service 
  tier: frontend
spec:
  selector:
    app:  movie-analist-ui
    tier: frontend
  type:  LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
