apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-analyst-ui
  template:
    metadata:
      labels:
        app: movie-analyst-ui
    spec:
      containers:
      - name: movie-analyst-ui
        image: gcr.io/ramp-up-247818/movie-analyst-api:0.1.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 125m
            memory: 120Mi
        ports:
        - containerPort: 3000
        