pipeline {
    agent any
    environment {
        GOOGLE_PROJECT_ID = 'ramp-up-247818';
        GOOGLE_SERVICE_ACCOUNT_KEY = credentials('JENKINS_SERVICE_ACCOUNT');
        HOME = '.'
    }
   
    stages {
        stage('terraform set up') {
            steps {
                dir('infrastructure/'){
                sh 'terraform -v'
                sh "terraform init"
                }

            }
        }
        stage('test plan') {
            steps {
            dir('infrastructure/'){ 
                 sh 'pwd'
                sh 'terraform plan'
            }
            }
        }
        stage('plan approval'){
        steps{
        script {
          def userInput = input(id: 'confirm', message: 'Apply Terraform?', parameters: [ [$class: 'BooleanParameterDefinition', defaultValue: false, description: 'Apply terraform', name: 'confirm'] ])
        }
        }
        }
        stage('deploy') {
            steps {
                sh "echo ---------------terraforming----------------------------"
                dir('infrastructure/'){
                sh "terraform apply -auto-approve"
                }
                sh "echo ---------------terraformed----------------------------"
        }
    }
}

}
