FROM node:current-alpine
WORKDIR /
RUN apk add git
ADD https://api.github.com/repos/danielperga97/movie-analyst-ui/git/refs/heads/develop version.json
RUN git clone https://github.com/Danielperga97/movie-analyst-api.git /movie-analist-api
WORKDIR /movie-analist-api
ENV BACK_HOST=movie-analist-api
ENV DB_USER=postgres
ENV DB_HOST=movie-analyst-api
ENV DB_NAME=movie_db
ENV DB_PASS=2045835202
RUN npm install 
RUN npm install pg
EXPOSE 3000
ENTRYPOINT npm start
