- name: jenkins auto configuration 
  hosts: all
  become: yes
  become_user: root
  become_method: sudo 
  tasks:
  - name: install java 
    yum:    
      name: java-1.8.0-openjdk-devel
      state: latest
  - name: add jenkins repo
    yum_repository:
      name: Jenkins-stable
      description: Jenkins YUM repo
      baseurl: http://pkg.jenkins.io/redhat-stable
      file: /etc/yum.repos.d/jenkins.repo
  - name: add jenkins key
    rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
  - name: install jenkins
    yum:
      name: jenkins
      state: present
  - name: start and enable Jenkins server
    service:
      name: jenkins
      state: started
      enabled: yes
  - name: create jenkins brick
    file:
      path: /home/jenkins/brick
      state: directory
      owner: jenkins
      recurse: yes
      mode: 777
    ignore_errors: true
  - name: create jenkins user shared home folder
    file:
      path: /home/jenkins/home
      state: directory
      owner: jenkins
      recurse: yes
      mode: 777
    ignore_errors: true
  - name: install wget
    yum: 
      name: wget
      state: latest
  - name: install centos gluster repo 
    yum: 
      name: centos-release-gluster
      state: latest
  - name: install centos epel release repo
    yum: 
      name: epel-release
      state: latest
  - name: install glusterfs server 
    yum:    
      name: glusterfs-server
      state: latest
  - name: install xfsprogs
    yum:    
      name: xfsprogs
      state: latest
  - name: start and enable glusterfs server
    service:
      name: glusterd
      state: started
      enabled: yes
  - name: create gluster volume
    gluster_volume:
      state: present
      name: jenkins_home
      bricks: /home/jenkins/brick
      rebalance: yes
      force: true
      cluster:
        - 10.20.0.31
        - 10.20.0.32
    run_once: true
  - name: mount gluster volume
    command: mount.glusterfs localhost:jenkins_home /home/jenkins/home
    ignore_errors: true
  - name: start gluster volume
    gluster_volume:
      state: started
      name: jenkins_home
  - name: stop jenkins
    service:
      name: jenkins
      state: stopped
  - name: move jenkins home folder
    copy:
      src: /var/lib/jenkins/
      dest: /home/jenkins/home
      remote_src: yes
      mode: 777
  - name: guarantee jenkins permission folder
    command: chmod 777 -R /home/jenkins/home
  - name: remove the folder
    file: 
      path: /var/lib/jenkins
      state: absent 
  - name: create symlink
    file:
      src: /home/jenkins/home
      dest: /var/lib/jenkins
      state: link
      force: yes
  - name: Ansible create file with content example
    copy:
      dest: "/etc/profile.d/variable.sh"
      content: |
        export JENKINS_HOME=/home/jenkins/home
  - name: source 
    shell: source "/etc/profile.d/variable.sh"
  - name: install nodejs 
    yum:    
      name: nodejs
      state: latest
  - name: install unzip 
    yum:
      name: unzip
      state: latest
  - name: download and extract terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.6/terraform_0.12.6_linux_amd64.zip
      dest: /usr/bin/
      remote_src: yes

  - name: Copy service account to jenkins server
    copy:
      src: /home/daniel/Documentos/Rampup-45f3b26c77de.json
      dest: /home/jenkins/Rampup-45f3b26c77de.json
      owner: jenkins
      mode: '0644'
  - name: Copy ssh key to jenkins server
    copy:
      src: /home/daniel/.ssh/google_compute_engine.pub
      dest: /home/jenkins/google_compute_engine.pub
      owner: jenkins
      mode: '0644'
  - name: Copy ssh key to jenkins server
    copy:
      src: /home/daniel/.ssh/google_compute_engine
      dest: /home/jenkins/google_compute_engine
      owner: jenkins
      mode: '0644'
  - name: Create dockerfiles directory
    file:
      path: /tmp/front-dockerfile
      state: directory
      mode: '0777'
  - name: install git   
    yum:
      name: git
      state: latest
  - name: install docker
    yum:
      name: docker
      state: latest
  - name: start and enable docker
    service:
      name: docker
      state: started
      enabled: yes
  - name: ensure group docker exists
    group:
      name: docker
      state: present
  - name: add jenkins user to docker group
    user:
      name: jenkins
      groups: docker
      state: present
      append: yes 
  - name: disable jenkins initialization password screen
    lineinfile:
      dest: /etc/sysconfig/jenkins
      regexp: '^(.*)JAVA_ARGS(.*)'
      line: 'JAVA_ARGS="-Djenkins.install.runSetupWizard=false"'
  - name: disable jenkins initialization password screen 2
    lineinfile:
      dest: /etc/sysconfig/jenkins
      regexp: '^(.*)JENKINS_JAVA_OPTIONS(.*)'
      line: 'JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'
  - name: create groovy init.d folder
    file:
      path: /var/lib/jenkins/init.groovy.d
      state: directory
      mode: "u=rw,g=rwx,o=rwx"
  - name: create default user 
    copy: 
      src: /home/daniel/Documentos/workspace_rampup/basic-security.groovy
      dest: /var/lib/jenkins/init.groovy.d/basic-security.groovy
  - name: guarantee jenkins permission folder
    command: chmod 777 -R /home/jenkins/home
  - name: restart jenkins service
    service: 
     name: jenkins 
     state: restarted
  - name: wait for jenkins to start
    wait_for:
      host: 0.0.0.0
      port: 8080
      delay: 120
  - name: install plugins 
    jenkins_plugin:
      name: "{{ item }}"
      url_username: jenkinsadmin
      url_password: "jenkinspassword"
      state: latest
      with_dependencies: yes
    ignore_errors: true
    with_items: 
      - cloudbees-folder
      - antisamy-markup-formatter
      - build-name-setter
      - build-timeout
      - config-file-provider
      - credentials-binding
      - embeddable-build-status
      - dashboard-view
      - rebuild
      - ssh-agent
      - throttle-concurrents
      - timestamper
      - ws-cleanup
      - ant
      - gradle
      - msbuild
      - nodejs
      - checkstyle
      - cobertura
      - htmlpublisher
      - junit
      - warnings
      - xunit
      - workflow-aggregator
      - github-organization-folder
      - pipeline-stage-view
      - build-pipeline-plugin
      - conditional-buildstep
      - jenkins-multijob-plugin
      - parameterized-trigger
      - copyartifact
      - bitbucket
      - clearcase
      - cvs
      - git
      - git-parameter
      - github
      - github-branch-source
      - gitlab-plugin
      - p4
      - repo
      - subversion
      - teamconcert
      - tfs
      - matrix-project
      - ssh-slaves
      - windows-slaves
      - matrix-auth
      - pam-auth
      - ldap
      - role-strategy
      - active-directory
      - email-ext
      - emailext-template
      - mailer
      - publish-over-ssh
      - ssh
  - name: reboot machine
    reboot:
  - name: wait for jenkins to start
    wait_for:
      host: 0.0.0.0
      port: 8080
      delay: 5
