plugin: gcp_compute
projects:
  - ramp-up-247818
zones:
  - "us-east1-b"
filters: 
  - 'name = anchore*'
auth_kind: serviceaccount
service_account_file: "/home/daniel/Documentos/Rampup-f6205223ec03.json"

